# Generated by Django 2.1.5 on 2019-02-09 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0030_auto_20181209_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='slot_count',
            field=models.PositiveIntegerField(default=1, help_text='How many times this talk will be held. Currently only editable by the organiser.', verbose_name='Slot Count'),
        ),
    ]
