# Generated by Django 2.1.5 on 2019-02-09 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0031_submission_slot_count'),
        ('schedule', '0011_auto_20180205_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='talkslot',
            name='slot_index',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='talkslot',
            unique_together={('submission', 'schedule', 'slot_index')},
        ),
    ]
